### ISSUE TITLE
pip install djangosanetesting fails with virtualenv on arch linux

### ISSUE THREAD

**Issue by honzakral** [Almad/django-sane-testing#13]
Command /usr/bin/python2.7 -c "import setuptools;**file**='/home/king/work/VENVS/petrol/build/djangosanetesting/setup.py';execfile(**file**)" install --single-version-externally-managed --record /tmp/pip-OtMQNR-record/install-record.txt --install-headers /home/king/work/VENVS/petrol/include/site/python2.7 failed with error code 1
Exception information:
Traceback (most recent call last):
  File "/home/king/work/VENVS/petrol/lib/python2.7/site-packages/pip-0.8.1-py2.7.egg/pip/basecommand.py", line 130, in main
    self.run(options, args)
  File "/home/king/work/VENVS/petrol/lib/python2.7/site-packages/pip-0.8.1-py2.7.egg/pip/commands/install.py", line 228, in run
    requirement_set.install(install_options, global_options)
  File "/home/king/work/VENVS/petrol/lib/python2.7/site-packages/pip-0.8.1-py2.7.egg/pip/req.py", line 1043, in install
    requirement.install(install_options, global_options)
  File "/home/king/work/VENVS/petrol/lib/python2.7/site-packages/pip-0.8.1-py2.7.egg/pip/req.py", line 559, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/home/king/work/VENVS/petrol/lib/python2.7/site-packages/pip-0.8.1-py2.7.egg/pip/__init__.py", line 249, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command /usr/bin/python2.7 -c "import setuptools;**file**='/home/king/work/VENVS/petrol/build/djangosanetesting/setup.py';execfile(**file**)" install --single-version-externally-managed --record /tmp/pip-OtMQNR-record/install-record.txt --install-headers /home/king/work/VENVS/petrol/include/site/python2.7 failed with error code 1

**Comment by honzakral** [comment]
the underlying exception is:

running install_lib

creating /usr/lib/python2.7/site-packages/djangosanetesting

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/king/work/VENVS/petrol/build/djangosanetesting/setup.py", line 7, in <module>

```
paver.tasks.main()
```

  File "paver-minilib.zip/paver/tasks.py", line 621, in main

  File "paver-minilib.zip/paver/tasks.py", line 604, in _launch_pavement

  File "paver-minilib.zip/paver/tasks.py", line 569, in _process_commands

  File "paver-minilib.zip/paver/setuputils.py", line 146, in **call**

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

```
cmd_obj.run()
```

  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 53, in run

```
return _install.run(self)
```

  File "/usr/lib/python2.7/distutils/command/install.py", line 575, in run

```
self.run_command(cmd_name)
```

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

```
self.distribution.run_command(command)
```

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

```
cmd_obj.run()
```

  File "/usr/lib/python2.7/site-packages/setuptools/command/install_lib.py", line 21, in run

```
outfiles = self.install()
```

  File "/usr/lib/python2.7/distutils/command/install_lib.py", line 115, in install

```
outfiles = self.copy_tree(self.build_dir, self.install_dir)
```

  File "/usr/lib/python2.7/site-packages/setuptools/command/install_lib.py", line 50, in copy_tree

```
return _install_lib.copy_tree(self, infile, outfile)
```

  File "/usr/lib/python2.7/distutils/cmd.py", line 377, in copy_tree

```
dry_run=self.dry_run)
```

  File "/usr/lib/python2.7/distutils/dir_util.py", line 159, in copy_tree

```
verbose=verbose, dry_run=dry_run))
```

  File "/usr/lib/python2.7/distutils/dir_util.py", line 139, in copy_tree

```
mkpath(dst, verbose=verbose)
```

  File "/usr/lib/python2.7/distutils/dir_util.py", line 76, in mkpath

```
"could not create '%s': %s" % (head, exc.args[-1]))
```

distutils.errors.DistutilsFileError: could not create '/usr/lib/python2.7/site-packages/djangosanetesting': Permission denied

**Comment by honzakral** [comment]
similar for installation with -e

pip install -e git+https://github.com/Almad/django-sane-testing.git#egg=djangosanetesting                                                                        (petrol)
Obtaining djangosanetesting from git+https://github.com/Almad/django-sane-testing.git#egg=djangosanetesting
  Cloning https://github.com/Almad/django-sane-testing.git to ./work/VENVS/petrol/src/djangosanetesting
  Running setup.py egg_info for package djangosanetesting
    no previously-included directories found matching 'djangosanetesting/*.pyc'
Installing collected packages: djangosanetesting
  Running setup.py develop for djangosanetesting
    install_dir /usr/lib/python2.7/site-packages/
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/king/work/VENVS/petrol/src/djangosanetesting/setup.py", line 7, in <module>
        paver.tasks.main()
      File "paver-minilib.zip/paver/tasks.py", line 621, in main
      File "paver-minilib.zip/paver/tasks.py", line 604, in _launch_pavement
      File "paver-minilib.zip/paver/tasks.py", line 569, in _process_commands
      File "paver-minilib.zip/paver/setuputils.py", line 146, in __call__
      File "/usr/lib/python2.7/distutils/dist.py", line 971, in run_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/usr/lib/python2.7/site-packages/setuptools/command/develop.py", line 51, in finalize_options
        easy_install.finalize_options(self)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 267, in finalize_options
        if not self.editable: self.check_site_dir()
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 399, in check_site_dir
        self.cant_write_to_target()
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 456, in cant_write_to_target
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: can't create or remove files in install directory

```
The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/test-easy-install-20838.write-test'
```

**Comment by Almad** [comment]
Can You plese provide more details, like setuptools and virtualenv version? I cannot reproduce that bug: 

almad@namtar ~/tmp $ mkdir venv
    almad@namtar ~/tmp $ cd venv/
    almad@namtar ~/tmp/venv $ virtualenv .
    source ./New python executable in ./bin/python2.6
    bAlso creating executable in ./bin/python
    iInstalling setuptools...       .........done.
    almad@namtar ~/tmp/venv $ source ./bin/activate
    (venv)almad@namtar ~/tmp/venv $ pip install djangosanetesting
    Downloading/unpacking djangosanetesting
    Downloading djangosanetesting-0.5.10.tar.gz (69Kb): 69Kb downloaded
    In the tar file /tmp/pip-kHKlWs-unpack/djangosanetesting-0.5.10.tar.gz the member djangosanetesting-0.5.10/README is invalid: 'NoneType' object has no attribute 'isreg'
    Running setup.py egg_info for package djangosanetesting
    warning: no files found matching 'README'
    no previously-included directories found matching 'djangosanetesting/_.pyc'
    Installing collected packages: djangosanetesting
    Running setup.py install for djangosanetesting
    warning: no files found matching 'README'
    no previously-included directories found matching 'djangosanetesting/_.pyc'
    Successfully installed djangosanetesting
    Cleaning up...
    (venv)almad@namtar ~/tmp/venv $ pip uninstall djangosanetesting
    Uninstalling djangosanetesting:
    /home/almad/tmp/venv/lib/python2.6/site-packages/djangosanetesting
    /home/almad/tmp/venv/lib/python2.6/site-packages/djangosanetesting-0.5.10-py2.6.egg-info
    Proceed (y/n)? y
    Successfully uninstalled djangosanetesting
    (venv)almad@namtar ~/tmp/venv $ pip install -e git+https://github.com/Almad/django-sane-testing.git#egg=djangosanetesting
    Obtaining djangosanetesting from git+https://github.com/Almad/django-sane-testing.git#egg=djangosanetesting
    Cloning https://github.com/Almad/django-sane-testing.git to ./src/djangosanetesting
    error: SSL certificate problem, verify that the CA cert is OK. Details:
    error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed while accessing https://github.com/Almad/django-sane-testing.git/info/refs

```
fatal: HTTP request failed
Complete output from command /usr/bin/git clone -q https://github.com/Almad/django-sane-testing.git /home/almad/tmp/venv/src/djangosanetesting:

----------------------------------------
Command /usr/bin/git clone -q https://github.com/Almad/django-sane-testing.git /home/almad/tmp/venv/src/djangosanetesting failed with error code 128
Storing complete log in /home/almad/.pip/pip.log
(venv)almad@namtar ~/tmp/venv $ pip install -e git+git://github.com/Almad/django-sane-testing.git#egg=djangosanetesting
Obtaining djangosanetesting from git+git://github.com/Almad/django-sane-testing.git#egg=djangosanetesting
Cloning git://github.com/Almad/django-sane-testing.git to ./src/djangosanetesting
Running setup.py egg_info for package djangosanetesting
no previously-included directories found matching 'djangosanetesting/*.pyc'
Installing collected packages: djangosanetesting
Running setup.py develop for djangosanetesting
no previously-included directories found matching 'djangosanetesting/*.pyc'
Creating /home/almad/tmp/venv/lib/python2.6/site-packages/djangosanetesting.egg-link (link to .)
Adding djangosanetesting 0.5.10 to easy-install.pth file

Installed /home/almad/tmp/venv/src/djangosanetesting
Successfully installed djangosanetesting
Cleaning up...
(venv)almad@namtar ~/tmp/venv $ 
```

**Comment by Almad** [comment]
Note to self: test with 2.7

**Comment by kvbik** [comment]
works for me.. archlinux.. how can i reproduce Honza's bug?

```
[kv@work django-sane-testing (master)]$ virtualenv KAKA
...
[kv@work django-sane-testing (master)]$ cd KAKA/
[kv@work KAKA (master)]$ source bin/activate
(KAKA)[kv@work KAKA (master)]$ pip install -e "git+https://github.com/Almad/django-sane-testing.git#egg=djangosanetesting"
...
(KAKA)[kv@work KAKA (master)]$ python
Python 2.7.1 (r271:86832, Jan  6 2011, 11:51:37)
[GCC 4.5.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import djangosanetesting
>>> djangosanetesting.__file__
'/home/kvbik/GIT/github/other/django-sane-testing/KAKA/src/djangosanetesting/djangosanetesting/__init__.py'
>>>
(KAKA)[kv@work KAKA (master)]$ virtualenv --version
1.5.1
```

**Comment by Almad** [comment]
OK, moving to backlog until reproduction info provided.
