### ISSUE TITLE
DST should retrieve sane traceback from Django HTTP errors

### ISSUE THREAD

**Issue by Almad** [Almad/django-sane-testing#3]
When server-side error occurs, client test failure is incomprehensible, even when using verbose pattern like:

```
    try:
        response = opener.open(request)
    except urllib2.HTTPError, err:
        if err.fp:
            error = ": %s" % err.fp.read()
        else:
            error = ''
        logging.error("Error occured while opening HTTP %s" % error)
        raise
    self.assertEquals(200, response.code)
    response.close()
```

Provide a helper plugin / function / wrapper that is able to parse normal traceback from Django HTML mess.

**Comment by Almad** [comment]
(This will fix http://devel.almad.net/trac/django-sane-testing/ticket/1 )

**Comment by Almad** [comment]
Fixed by yed

**Comment by Almad** [comment]
This is actually not working, as exposed by tests now:

```
======================================================================
FAIL: testproject.test.test_liveserver.TestSelenium.test_selenium_server_error
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lukas.linhart/projects/django-sane-testing/lib/python2.6/site-packages/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/home/lukas.linhart/projects/django-sane-testing/testproject/test/test_liveserver.py", line 72, in test_selenium_server_error
    self.assert_not_equals("500 Server error, traceback not found", err.msg)
AssertionError: '500 Server error, traceback not found' == '500 Server error, traceback not found'
```

**Comment by Almad** [comment]
Works for common HTTP errors, but not via selenium - selenium moving to backlog.
