### ISSUE TITLE
Error with some magic dependency combination

### ISSUE THREAD

**Issue by Almad** [Almad/django-sane-testing#37]
> > > import djangosanetesting
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/big/var/buildslaves/63/109/build/lib/python2.5/site-packages/djangosanetesting/**init**.py", line 6, in <module>
> > >     from djangosanetesting.testrunner import *
> > >   File "/big/var/buildslaves/63/109/build/lib/python2.5/site-packages/djangosanetesting/testrunner.py", line 9, in <module>
> > >     from django.test import utils
> > >   File "/big/var/buildslaves/63/109/build/lib/python2.5/site-packages/django/test/**init**.py", line 5, in <module>
> > >     from django.test.client import Client, RequestFactory
> > >   File "/big/var/buildslaves/63/109/build/lib/python2.5/site-packages/django/test/client.py", line 21, in <module>
> > >     from django.test import signals
> > > ImportError: cannot import name signals

**Comment by brent-hoover** [comment]
Hi, is this issue still valid? If so can you provide some more info as to what environment you were running this in?
