### ISSUE TITLE
pip install djangosanetesting fails

### ISSUE THREAD

**Issue by honzakral** [Almad/django-sane-testing#7]
depends on paver

Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/king/work/VENVS/whiskey/build/djangosanetesting/setup.py", line 6, in <module>

```
import paver.tasks
```

ImportError: No module named paver.tasks

**Comment by Almad** [comment]
Oups, sdist did not bundled minilib.

**Comment by Almad** [comment]
Should be fixed with 0.5.10.
